import React from "react";
import {Session} from "next-auth";
import AuthProvider from "../providers/authProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({
                                    session,
                                       children,
                                   }: {
    session: Session
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>

        <main>
            <AuthProvider session={session}>
                {children}

            </AuthProvider>
        </main>
        </body>
        </html>
    )
}