'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Vafs6r9SUCb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Cormorant_Garamond } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import {getSession, signOut, useSession} from "next-auth/react";
import {redirect, useRouter} from "next/navigation";

export function Page404() {
    const {data: session} = useSession()
    const router = useRouter()

    const logout  = async () => {
        await signOut({
            redirect: true,
            callbackUrl: '/'
        })

    }
  return (
    <div className="flex flex-col items-center gap-2 py-16 text-center">
      <div className="space-y-2">
        <h1 className="text-4xl font-extrabold tracking-tighter sm:text-5xl md:text-6xl">404 Not Found</h1>
        <p className="text-gray-500 dark:text-gray-400">Sorry, we couldn't find the page you're looking for.</p>
      </div>
        {
            session ? <Button className="mx-auto w-[200px]" onClick={() => logout()}>Logout</Button> : ''
        }

    </div>
  )
}
