/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sfKzv53jG2B
 */
import { Button } from "@/components/ui/button"
import {signIn} from "next-auth/react";

export function Login() {

  return (
    <div className="flex items-center justify-center min-h-screen px-4">
      <div className="w-full max-w-sm space-y-4">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold">Login</h1>
          <p className="text-gray-500 dark:text-gray-400">You must login with Discord to access this page</p>
        </div>
        <Button onClick={() => signIn()} className="w-full">
          <DiscIcon className="mr-2 h-5 w-5" />
          Login with Discord
        </Button>
      </div>
    </div>
  )
}


function DiscIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}
