/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Zyc5SQvPlSW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function PrivacyPage() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Privacy Policy</h1>
          <p className="mt-4 text-lg text-muted-foreground">
            At Tickettr, we are committed to protecting the privacy and security of your personal
            information. This privacy policy outlines how we collect, use, and safeguard your data.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Data Collection</h2>
          <p className="mt-4 text-muted-foreground">Our Discord ticket bot collects the following user data:</p>
          <ul className="mt-4 space-y-2 text-muted-foreground">
            <li>
              <span className="font-medium text-foreground">user id:</span>
              Your Discord id, which is used to identify you within the ticket system.
            </li>
            <li>
              <span className="font-medium text-foreground">Server ID:</span>
              The unique identifier of the Discord server where the ticket was created, which allows us to provide
              server-specific support.
            </li>
            <li>
              <span className="font-medium text-foreground">Ticket Content:</span>
              The text and any attachments you provide within the ticket, which we store for your easy access
            </li>
          </ul>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Data Storage</h2>
          <p className="mt-4 text-muted-foreground">
            We take the security of your data seriously. All user information collected by our Discord ticket bot is
            stored securely on encrypted servers. Access to this data is restricted to only the necessary personnel who
            require it to provide support and maintain the bot's functionality.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Data Sharing</h2>
          <p className="mt-4 text-muted-foreground">
            We do not share or sell any user data collected by our Discord ticket bot to third parties. The only
            exception is if we are required to do so by law or to protect the rights, property, or safety of our
            organization, our users, or the public.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">User Rights</h2>
          <p className="mt-4 text-muted-foreground">
            You have the right to access, update, or delete the data we have collected about you. To exercise these
            rights, please contact our support team at support@tickettr.xyz. We will respond to your request within 30
            days.
          </p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Policy Changes</h2>
          <p className="mt-4 text-muted-foreground">
            We may update this privacy policy from time to time. If we make any significant changes, we will notify you
            by posting the updated policy on our website and within the Discord server where the bot is hosted. We
            encourage you to review this policy periodically to stay informed about how we are protecting your data.
          </p>
        </div>
      </div>
    </div>
  )
}
