/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VNOdI4hMsAX
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function TOSPage() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="space-y-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-foreground">Terms of Service</h1>
          <p className="mt-4 text-muted-foreground">Effective Date: {new Date().toLocaleDateString()}</p>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Definitions</h2>
          <div className="mt-4 space-y-4 text-muted-foreground">
            <p>In these Terms of Service, the following definitions apply:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>
                <strong>Service:</strong> The Discord Bot, website, and related services provided by our company.
              </li>
              <li>
                <strong>User:</strong> Any individual or entity that accesses or uses the Service.
              </li>
              <li>
                <strong>Content:</strong> Any information, data, text, images, or other materials uploaded, submitted,
                or displayed on the Service by Users.
              </li>
            </ul>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">User Obligations</h2>
          <div className="mt-4 space-y-4 text-muted-foreground">
            <p>By using the Service, you agree to the following obligations:</p>
            <ul className="list-disc space-y-2 pl-6">
              <li>Use the Service only for lawful purposes and in accordance with these Terms of Service.</li>
              <li>Refrain from engaging in any activity that could harm the Service or other Users.</li>
              <li>Respect the intellectual property rights of our company and other Users.</li>
              <li>Provide accurate and up-to-date information when creating an account or using the Service.</li>
            </ul>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Intellectual Property</h2>
          <div className="mt-4 space-y-4 text-muted-foreground">
            <p>
              The Service, including its design, content, and underlying technology, is owned by our company and
              protected by copyright, trademark, and other intellectual property laws. Users may not modify, copy,
              distribute, transmit, display, reproduce, or create derivative works from the Service without our prior
              written consent.
            </p>
            <p>
              Users retain ownership of the Content they upload, submit, or display on the Service. However, by using
              the Service, Users grant our company a non-exclusive, royalty-free, worldwide license to use, reproduce,
              modify, and display the Content for the purpose of providing and improving the Service.
            </p>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Termination</h2>
          <div className="mt-4 space-y-4 text-muted-foreground">
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, for any reason,
              including if we reasonably believe that you have violated these Terms of Service. Upon termination, you
              will no longer be able to access your account or the Content you have stored on the Service.
            </p>
            <p>
              Sections of these Terms of Service that, by their nature, should survive termination will remain in full
              force and effect after any such termination.
            </p>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Limitation of Liability</h2>
          <div className="mt-4 space-y-4 text-muted-foreground">
            <p>
              In no event shall our company be liable for any indirect, special, incidental, or consequential damages
              arising out of or in connection with the Service, including but not limited to lost profits, business
              interruption, or loss of data.
            </p>

          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Governing Law and Dispute Resolution</h2>
          <div className="mt-4 space-y-4 text-muted-foreground">
            <p>
              These Terms of Service shall be governed by and construed in accordance with the laws of [Jurisdiction].
              Any disputes arising out of or in connection with these Terms of Service shall be resolved through binding
              arbitration in accordance with the rules of [Arbitration Organization].
            </p>
          </div>
        </div>
        <div>
          <h2 className="text-2xl font-bold tracking-tight text-foreground">Changes to the Terms of Service</h2>
          <div className="mt-4 space-y-4 text-muted-foreground">
            <p>
              We reserve the right to modify these Terms of Service at any time. Any changes will be effective
              immediately upon posting the updated terms on the Service. Your continued use of the Service after such
              changes constitutes your acceptance of the new Terms of Service.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
