name: Update Hash On Pull

on:
  push:
    branches:
      - main

jobs:
  update-enviornment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Short Hash
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "Fetched commit hash: $COMMIT_HASH"

      - name: Push Hash to Environment
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" > .env
